version: "3"

volumes:
  db-data:
  bundle:
  node_modules:

services:
  web:
    build:
      context: .
      dockerfile: "DEV.Dockerfile"
    # 開発環境用の設定: bundle exec rails s -p 3000 -b '0.0.0.0'
    # 本番環境を再現する場合: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle:cached'
      - 'node_modules:/app/node_modules'
      - '/app/vendor'
      - '/app/tmp'
      - '/app/log'
      - '/app/.git'
    environment:
      - 'DATABASE_PASSWORD=postgres'
      # 開発環境用:'RAILS_ENV=development'
      # 本番環境を開発環境で再現する場合: 'RAILS_ENV=production'
      - 'RAILS_ENV=development'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
